name: Lint

on:
  push:
    branches: [ feature2 ]
    paths:
      - 'factorial.py'
      - 'lint.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Debug information
      run: echo "runing on ${{ RUNNER.OS }}"
    - run: echo "The name of the branch is ${{ GITHUB.REF }} in repo. ${{ GITHUB.REPOSITORY }}"
    - name: check-out the code
      uses: actions/checkout@v2
    - name: debug repository name
      run: echo "The ${{ GITHUB.REPOSITORY }} has been cloned to the runner"
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python_version: 3.9
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.11.1
    - name: Lint with pylint
      run: |
        python lint_test.py
    - name: build container
      run: |
        echo: "building docker container..."
        sleep 60
        echo: "The docker container is built successfully"
    - name: Deploy
      run: |
        echo: "Deploing docker container..."
        sleep 60
        echo: "Deploing container is built successfully"
    - run: echo "the job status is ${{ JOB.STATUS }}"
